name: C/C++ CI

on:
  push:
    branches: [ tarnish-0.1 ]
  pull_request:
    branches: [ tarnish-0.1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: make Phoenix.app
