name: C/C++ CI

on:
  push:
    branches: [ tarnish-0.1 ]
  pull_request:
    branches: [ tarnish-0.1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install sfml
      run: sudo apt-get update && sudo apt-get install libsfml-dev
    - name: get submodules
      run: git status
    - name: make
      run: make Tarnish.app
